export default {
    BE_ERRORS: {
        UNKNOWN_SUBERROR_MESSAGE: 'UNKNOWN_SUBERROR_MESSAGE',
        ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
        VALIDATION_ERROR: 'VALIDATION_ERROR',
        INVALID_PARAMETERS: 'INVALID_PARAMETERS',
        CANNOT_LOG_IN: 'CANNOT_LOG_IN',
        INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
        UNAUTHORIZED: 'UNAUTHORIZED',
        FORBIDDEN: 'FORBIDDEN',
        USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
        EXPIRED_TOKEN: 'EXPIRED_TOKEN'
    }
}